spring:
  application:
    name: customer-management
server:
  port: 9090
---
logging:
  level:
    root: DEBUG

springdoc:
  packagesToScan: com.customermanagment
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html


customer-management:
  getAll: /customers/getAll
  findById: /customers
  error: /error
