spring:
  application:
    name: customer-management
server:
  port: 9090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true


customer-management:
  getAll: /customers/getAll
  findByIds: /customers
  findById: /customers/{id}
  addCustomer: /customers
  updateCustomer: /customers
  deleteCustomer: /customers/{id}
  error: /error

partiton-ids:
  size: 5

uri.prefix:
  customer: /customers
