spring:
  application:
    name: customer-management
server:
  port: 9090
---
logging:
  level:
    root: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true


customer-management:
  getAll: /customers/getAll
  findById: /customers
  error: /error
